### ISSUE TITLE
Synchronous support

### ISSUE THREAD

**Issue by denizsincar29** [JacobLinCool/gradio-rs#2]
Hello. Is there a way to use gradio client synchronously? My whole app is synchronous so I don't want to rewrite it. Thank you.

**Comment by JacobLinCool** [comment]
I could try adding a synchronous API.

Before the asynchronous API is done, you can try using [block_on](https://docs.rs/tokio/latest/tokio/runtime/struct.Runtime.html#method.block_on) to run an asynchronous function in a synchronous context, I think.

**Comment by JacobLinCool** [comment]
Hi @denizsincar29,

The synchronization API is now available in `0.2.3`, try using the `*_sync` functions. You can check out the ["hello-sync"](https://github.com/JacobLinCool/gradio-rs/blob/main/examples/hello-sync.rs) example to see usage.

**Comment by denizsincar29** [comment]
Oh thank you so much. That's cool. Just wanted to ask if it also supports wasm?

**Comment by JacobLinCool** [comment]
I think it's possible, but I may need to figure out the right feature flags for Tokio and Reqwest.

If you're interested in that, here are some references you may need:
- https://docs.rs/tokio/latest/tokio/#wasm-support
- https://docs.rs/reqwest/latest/reqwest/#wasm

However, Gradio already has an official JS client, so you may want to try it in your WASM environment if it also supports JS.

> Move WASM support to a new issue: https://github.com/JacobLinCool/gradio-rs/issues/3
